export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { FC, PropsWithChildren } from "react";
import { Toaster } from "react-hot-toast";
import Footer from "~/components/layout/footer";
import "~/styles/globals.css";
import Navbar from "./components/navbar";
import RootProviders from "./providers";

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="se">
      <body>
        <Analytics mode="auto" />
        <SpeedInsights />
        <Toaster position="top-center" reverseOrder={false} />
        <RootProviders>
          <div className="zWhite flex min-h-screen flex-col">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </RootProviders>
      </body>
    </html>
  );
};

export default RootLayout;
