name: Build image
run-name: Building docker image and pushing to github container registry

# specifies permissions for the `secrets.GITHUB_TOKEN` token
permissions:
  contents: read
  packages: write

# trigger
on:
  push:
    branches: 
    - "dev"
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # bakes branch name into image tag (aka both image name and image destination (same thing i think))
      IMAGE_TAG: ghcr.io/z-teknologsektionen/ztek:${{github.ref_name}}
    steps:

    - name: checkout repository
      uses: actions/checkout@v6   

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build image
      run:  docker build -t $IMAGE_TAG ${{ github.workspace }}

    - name: push image
      run:  docker push $IMAGE_TAG
    


# ********** ********** **********
#
# for reference on ${​{contexts}​}, see
# https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
#
# ********** ********** **********